<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>PromptHelper</AssemblyName>
    <RootNamespace>PromptHelper</RootNamespace>

    <Version>0.1.0</Version>

    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>